x = input("ingrese el primer numero:"   )
y= input("ingrese el segundo numero:"  )
suma = int(x) + int(y)
print("la suma es:" , suma)
resta = int(x) - int(y)
print("la resta es:" , resta)
multiplicacion = int(x) * int(y)
print("la multiplicacion es:" , multiplicacion)
division = int(x) / int(y)
print("la division es:" , division)
print("la potencia es:" , int(x) ** int(y)
      )